version: '1.0.{build}'
image: Visual Studio 2019

environment:
  nodejs_version: 10.9
  COVERALLS_REPO_TOKEN:
  secure: yFVffx+aDg1QMtDKWWFtNyKPVHFKEQ1c81VTMU08CUed4m1FaI2oryr86oAZQs4Y
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./WebApplication3.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./WebApplication3.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\bin\Debug\netcoreapp3.0\publish'
   name: WebApplication3
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./NUnitTestProject2/NUnitTestProject2.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test
after_test: 
# generate report for NUnit testing framework:
    - cmd: packages\opencover\4.7.922\tools\OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test" -output:coverage.xml -oldStyle -register:user -filter:"+[NUnitTestProject2*]*"  -output:coverage.xml

# generate report for MSTest testing framework:
#    -cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:YOURPROJECT.Tests/bin/debug/YOURPROJECT.Tests.dll" -output:coverage.xml
        
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%
on_finish :
  # any cleanup in here
    deploy: off
